name: dsire
favicon: null
layout_spectrum: 0.94493
typography_spectrum: 0.5352550356183201
title: Creative digital development
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a160a'
    - '#9bb4d8'
    - '#2480fd'
    - '#b0001e'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
