name: dsire
favicon: null
layout_spectrum: 0.3802048536017537
typography_spectrum: 0.5352550356183201
title: Creative digital development
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6891158048529178
  lightness: 0.11324898526072502
  saturation: 0.3439557075034827
  rhythmicContrast: 0.00004147249273955822
purpose: []
